name: python_setup

on:
  push:

jobs:
  python_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4        

      - name: Set up Python
        uses: actions/setup-python@v5   
        with:
          python-version: '3.9'
      - name: Dependency installation
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
      - name: Python version check present
        run: python --version
      - name: Flake8 version printed
        run: flake8 --version
      - name: Pytest version printed
        run: pytest --version