name: secret_workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Use secret
        run: echo "The secret is \${{ secrets.SECRET }}"
  # python_setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'

  #     - name: Dependency installation
  #       run: pip install pytest flake8

  #     - name: Python version verification
  #       run: python --version

  #     - name: Flake8 check
  #       run: flake8 --version

  #     - name: Pytest check
  #       run: pytest --version